# Generated by Django 3.2.5 on 2021-07-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='course',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='users',
            new_name='username',
        ),
    ]
