# Generated by Django 3.2.5 on 2021-07-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210708_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='username',
        ),
    ]
