# Generated by Django 3.2.5 on 2021-07-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210709_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='enrolledcourse',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
    ]
