# Generated by Django 3.2.5 on 2021-07-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210710_1912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrolledCourse',
        ),
    ]
