# Generated by Django 3.2.5 on 2021-07-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_enrolledcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistModel',
        ),
    ]
